---
title: "fEBA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fEBA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r , include = FALSE}
knitr::opts_chunk$set(collapse = TRUE , comment = "#>" , cache = TRUE)
```

```{r setup}
library(EFBA)

######################################
## Setting 1: Functional White Noise
######################################

# Simulate functional white noise

# Input parameters
nb <- 15 # Number of basis functions used to generate white noise
R <- 5 # Number of points in functional domain
Ts <- 200 # Length of time series
seed <- 234 # Seed for reproducibility

X <- fws.sim(nb = nb , gsz = R , Ts = Ts , seed = seed)

# Estimate and visualize power spectrum estimates for specific components
B <- 5 # Number of time blocks
N <- Ts / B # Number of observations per time block
bw <- 0.04 # Bandwidth for multitaper spectral estimator
K <- max(1 , floor(bw * (N + 1) - 1)) # Number of tapers for multitaper spectral estimator
std <- FALSE # Standardize variance for points in functional domain (TRUE) or not (FALSE)
freq <- seq(from = 0 , by = 1 / N , length.out = floor(N / 2) + 1) # Fourier frequencies
Rsel <- 4 # Number of points in functional domain used for test statistics
pse <- fhat_pmt(X , N , K , Rsel , std) # Changed fhat to fhat_pmt

cmpnt <- "1-1" # Select component to view
dimnames(pse) <- list(freq , apply(expand.grid(1:Rsel , 1:Rsel) , 1 , paste , collapse = "-") , 1:B)
image.plot(x = (1:B) * (Ts / B) , y = as.numeric(rownames(pse)) , z = t(Re(pse[ , cmpnt , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Multitaper Autospectrum' , 
           xlab = 'Time' , ylab = 'Hz' , xaxs = "i")


# Run fEBA algorithm

# Input parameters
set.seed(47)
ndraw <- 10000 # Number of draws from Gaussian process for approximating p-values
blockdiag <- TRUE # Use block diagonal covariance matrix approximation
dcap <- 40 # Max number of frequencies tested in a given pass 
alpha <- 0.05 / ceiling((1 - 2 * bw / 0.5) * (floor(N / 2) + 1) / dcap) # Alpha with Bonferroni correction

run.wn <- fEBA.wrapper(X , Rsel , K , N , ndraw , alpha , std , blockdiag , dcap)
print(run.wn$summary)

# View test statistics and p-values over frequencies
tmp <- cbind(as.numeric(unlist(lapply(run.wn$log , function(x) rownames(x$Qint)))) , 
             unlist(lapply(run.wn$log , function(x) x$Qint)) , 
             unlist(lapply(run.wn$log , function(x) x$Qpv[ , 'Qint'])))
tmp <- tmp[!duplicated(tmp[ , 1]) , ]

plot(tmp[ , 1] , tmp[ , 2] , type = "l" , xlab = 'Hz' , ylab = 'Qint')
plot(tmp[ , 1] , tmp[ , 3] , type = "l" , xlab = 'Hz' , ylab = 'p-value' , ylim = c(0 , 1))

##############################################
## Setting 2: Nonstationary 3 Band (Linear)
##############################################

# Three frequency bands
# (0 , 0.15]
# (0.15 , 0.35]
# (0.35 , 0.5]

# Simulate nonstationary 3 band linear

# Input parameters
nb <- 15 # Number of basis functions used to generate white noise
R <- 5 # Number of points in functional domain
Ts <- 200 # Length of time series
seed <- 634 # Seed for reproducibility

X <- f3bL.sim(nb = nb , gsz = R , Ts = Ts , seed = seed)

# Estimate and visualize power spectrum estimates for specific components
B <- 5 # Number of time blocks
N <- Ts / B # Number of observations per time block
bw <- 0.04 # Bandwidth for multitaper spectral estimator
K <- max(1 , floor(bw * (N + 1) - 1)) # Number of tapers for multitaper spectral estimator
std <- FALSE # Standardize variance for points in functional domain (TRUE) or not (FALSE)
freq <- seq(from = 0 , by = 1 / N , length.out = floor(N / 2) + 1) # Fourier frequencies
Rsel <- 4 # Number of points in functional domain used for test statistics
pse <- fhat_pmt(X , N , K , Rsel , std)

cmpnt <- "1-1" # Select component to view
dimnames(pse) <- list(freq , apply(expand.grid(1:Rsel , 1:Rsel) , 1 , paste , collapse = "-") , 1:B)
image.plot(x = (1:B) * (Ts / B) , y = as.numeric(rownames(pse)) , z = t(Re(pse[ , cmpnt , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Multitaper Autospectrum' , 
           xlab = 'Time' , ylab = 'Hz' , xaxs = "i")

# Run fEBA algorithm

# Input parameters
set.seed(734)
ndraw <- 10000 # Number of draws from Gaussian process for approximating p-values
blockdiag <- TRUE # Use block diagonal covariance matrix approximation
dcap <- 40 # Max number of frequencies tested in a given pass 
alpha <- 0.05 / ceiling((1 - 2 * bw / 0.5) * (floor(N / 2) + 1) / dcap) # Alpha with Bonferroni correction

run.3bL <- fEBA.wrapper(X , Rsel , K , N , ndraw , alpha , std , blockdiag , dcap)
print(run.3bL$summary)

# View test statistics and p-values over frequencies
tmp <- cbind(as.numeric(unlist(lapply(run.3bL$log , function(x) rownames(x$Qint)))) , 
             unlist(lapply(run.3bL$log , function(x) x$Qint)) , 
             unlist(lapply(run.3bL$log , function(x) x$Qpv[ , 'Qint'])))
tmp <- tmp[!duplicated(tmp[ , 1]) , ]

plot(tmp[ , 1] , tmp[ , 2] , type = "l" , xlab = 'Hz' , ylab = 'Qint')
plot(tmp[ , 1] , tmp[ , 3] , type = "l" , xlab = 'Hz' , ylab = 'p-value' , ylim = c(0 , 1))

##################################################
## Setting 3: Nonstationary 3 Band (Sinusoidal)
##################################################

# Three frequency bands
# (0 , 0.15]
# (0.15 , 0.35]
# (0.35 , 0.5]

# Simulate nonstationary 3 band sinusoidal

# Input parameters
nb <-15 # Number of basis functions used to generate white noise
R <- 5 # Number of points in functional domain
Ts <- 200 # Length of time series
seed <- 123 # Seed for reproducibility

X <- f3bS.sim(nb = nb , gsz = R , Ts = Ts , seed = seed)

# Estimate and visualize power spectrum estimates for specific components
B <-10 # Number of time blocks
N = Ts / B # Number of observations per time block
bw <- 0.04 # Bandwidth for multitaper spectral estimator
K <- max(1 , floor(bw * (N + 1) - 1)) # Number of tapers for multitaper spectral estimator
std <- FALSE # Standardize variance for points in functional domain (TRUE) or not (FALSE)
freq <- seq(from = 0 , by = 1 / N , length.out = floor(N / 2) + 1) # Fourier frequencies
Rsel <- 4 # Number of points in functional domain used for test statistics
pse <- fhat_pmt(X , N , K , Rsel , std)

cmpnt <- "1-1" # Select component to view
dimnames(pse) <- list(freq , apply(expand.grid(1:Rsel , 1:Rsel) , 1 , paste , collapse = "-") , 1:B)
image.plot(x = (1:B) * (Ts / B) , y = as.numeric(rownames(pse)) , z = t(Re(pse[ , cmpnt , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Multitaper Autospectrum' , 
           xlab = 'Time' , ylab = 'Hz' , xaxs = "i") 


# Run fEBA algorithm

# Input parameters
set.seed(435)
ndraw <- 10000 # Number of draws from Gaussian process for approximating p-values
blockdiag <- TRUE # Use block diagonal covariance matrix approximation
dcap <- 40 # Max number of frequencies tested in a given pass 
alpha <- 0.05 / ceiling((1 - 2 * bw / 0.5) * (floor(N / 2) + 1) / dcap) # Alpha with Bonferroni correction

run.3bS <- fEBA.wrapper(X , Rsel , K , N , ndraw , alpha , std , blockdiag , dcap)
print(run.3bS$summary)

# View test statistics and p-values over frequencies
tmp <- cbind(as.numeric(unlist(lapply(run.3bS$log , function(x) rownames(x$Qint)))) , 
             unlist(lapply(run.3bS$log , function(x) x$Qint)) , 
             unlist(lapply(run.3bS$log , function(x) x$Qpv[ , 'Qint'])))
tmp <- tmp[!duplicated(tmp[ , 1]) , ]

plot(tmp[ , 1] , tmp[ , 2] , type = "l" , xlab = 'Hz' , ylab = 'Qint')
plot(tmp[ , 1] , tmp[ , 3] , type = "l" , xlab = 'Hz' , ylab = 'p-value' , ylim = c(0 , 1))

```
