---
title: "mEBA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mEBA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r , include = FALSE}
knitr::opts_chunk$set(collapse = TRUE , comment = "#>" , cache = TRUE)
```

```{r simL3B}
library(EFBA)

# Output from msboot function is a list of the following 7 objects:
# 1) A list of matrices containing the test statistics over the Fourier frequencies for each W
# 2) A list of matrices containing the bootstrap test statistics over the Fourier frequencies for each W
# 3) A list of matrices containing the p-values for testing each Fourier frequency as a partition point for each W
# 4) A matrix indicating whether or not each frequency was identified as a partition point
# 5) A list of matrices containing the test statistics for each component over the Fourier frequencies for each W
# 6) A list of arrays containing the bootstrap test statistics for each component over the Fourier frequencies for each W
# 7) A list of matrices containing the p-values for each component testing each Fourier frequency as a partition point for each W

set.seed(523)

t <- 200 # Length of time series
R <- 10 # Number of components

########################
## Linear 3 Band (L3B)
########################
# Simulate data
X.l3b <- matrix(NA , nrow = t , ncol = R)
df <- meba.simdata(t + 200)
ll <- seq(from = 0 , by = -1 , length.out = R) # ll as c(0,-1,-2,-3,..)
cf <- rep(1 , R) # Same for all cf as 1

for (m in 1:R){
  X.l3b[ , m] <- cf[m] * df$bL[(101 + ll[m]):(t + 100 + ll[m])]
}

# Plot series 
plot.ts(X.l3b , main = "Linear 3 Band")

# Compute and plot local periodogram and demeaned local periodogram
N <- 2 * floor(t ^ 0.7) - floor(t ^ 0.7 / 2) * 2 # Neighborhood for local periodogram
freq <- seq(0 , floor(N / 2) , by = 1) / N
pse <- fhat_lp(X.l3b , N , stdz = FALSE)
gpse <- ghat(pse)


idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(gpse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Demeaned Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

# Run algorithm and store results
l3b.out <- msboot(nrep = 1000 , X.l3b , Wsel = 3 , stdz = FALSE , ncore = 1)


# Plot output
# Plot of observed test statistics across frequencies (red) and the first 50 bootstrap test statistics (black) for each W
par(mfrow = c(3 , 1))
plot(l3b.out[[2]][[1]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W1' , ylim = c(0 , 3000))
apply(l3b.out[[2]][[1]][ , 3:50] , 2 , function(x) lines(cbind(l3b.out[[2]][[1]][ , 1] , x)))
lines(l3b.out[[1]][[1]] , col = 'red' , lwd = 2)

plot(l3b.out[[2]][[2]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W2' , ylim = c(0 , 3000))
apply(l3b.out[[2]][[2]][ , 3:50] , 2 , function(x) lines(cbind(l3b.out[[2]][[2]][ , 1] , x)))
lines(l3b.out[[1]][[2]] , col = 'red' , lwd = 2)

plot(l3b.out[[2]][[3]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W3' , ylim = c(0 , 3000))
apply(l3b.out[[2]][[3]][ , 3:50] , 2 , function(x) lines(cbind(l3b.out[[2]][[3]][ , 1] , x)))
lines(l3b.out[[1]][[3]] , col = 'red' , lwd = 2)

# Plot of p-values for testing each frequency as a partition point (black) and 0.05 threshold (red) for each W
par(mfrow = c(3 , 1))
plot(l3b.out[[3]][[1]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(l3b.out[[3]][[2]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(l3b.out[[3]][[3]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

# Table of significant frequency partition points (none in the white noise case)
l3b.out[[4]][which(l3b.out[[4]][ , 2] == 1) , 1]

# Local periodogram with estimated cutpoints
idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")
abline(h = l3b.out[[4]][which(l3b.out[[4]][ , 2] == 1) , 1] , col = 'green' , lwd = 2)

```

```{r simM3B1}
set.seed(854)

t <- 200 # Length of time series
R <- 10 # Number of components

############################
## Mixture 3 Band (M3B-1)
############################
# Simulate data
X.m3b1 <- matrix(NA , nrow = t , ncol = R)
df <- meba.simdata(t + 200)
ll <- seq(from = 0 , by = -1 , length.out = R) # ll as c(0,-1,-2,-3,..)
cf <- rep(1 , R) # Same for all cf as 1

for (m in 1:floor(R / 2)){
  X.m3b1[ , m] <- cf[m] * df$bL[(101 + ll[m]):(t + 100 + ll[m])]
}      

for (m in (floor(R / 2) + 1):R){
  X.m3b1[ , m] <- cf[m] * df$bS[(101 + ll[m]):(t + 100 + ll[m])]
}

# Plot series 
plot.ts(X.m3b1 , main = "Mixture 3 Bands")

# Compute and plot local periodogram and demeaned local periodogram
N <- 2 * floor(t ^ 0.7) - floor(t ^ 0.7 / 2) * 2 # Neighborhood for local periodogram
freq <- seq(0 , floor(N / 2) , by = 1) / N
pse <- fhat_lp(X.m3b1 , N , stdz = FALSE)
gpse <- ghat(pse)

idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(gpse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Demeaned Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

# Run algorithm and store results
m3b1.out <- msboot(nrep = 1000 , X.m3b1 , Wsel = 3 , stdz = FALSE , ncore = 1)

# Plot output
# Plot of observed test statistics across frequencies (red) and the first 50 bootstrap test statistics (black) for each W
par(mfrow = c(3 , 1))
plot(m3b1.out[[2]][[1]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W1' , ylim = c(0 , 50000))
apply(m3b1.out[[2]][[1]][ , 3:50] , 2 , function(x) lines(cbind(m3b1.out[[2]][[1]][ , 1] , x)))
lines(m3b1.out[[1]][[1]] , col = 'red' , lwd = 2)

plot(m3b1.out[[2]][[2]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W2' , ylim = c(0 , 50000))
apply(m3b1.out[[2]][[2]][ , 3:50] , 2 , function(x) lines(cbind(m3b1.out[[2]][[2]][ , 1] , x)))
lines(m3b1.out[[1]][[2]] , col = 'red' , lwd = 2)

plot(m3b1.out[[2]][[3]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W3' , ylim = c(0 , 50000))
apply(m3b1.out[[2]][[3]][ , 3:50] , 2 , function(x) lines(cbind(m3b1.out[[2]][[3]][ , 1] , x)))
lines(m3b1.out[[1]][[3]] , col = 'red' , lwd = 2)

# Plot of p-values for testing each frequency as a partition point (black) and 0.05 threshold (red) for each W
par(mfrow = c(3 , 1))
plot(m3b1.out[[3]][[1]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(m3b1.out[[3]][[2]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(m3b1.out[[3]][[3]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

# Table of significant frequency partition points (none in the white noise case)
m3b1.out[[4]][which(m3b1.out[[4]][ , 2] == 1) , 1]


# Local periodogram with estimated cutpoints
idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")
abline(h = m3b1.out[[4]][which(m3b1.out[[4]][ , 2] == 1) , 1] , col = 'green' , lwd = 2)
```

```{r M3B2}
set.seed(567)

t <- 200 # Length of time series
R <- 10 # Number of components

############################################
## Differing Proportions 3 Band (M3B-2)
############################################
# Simulate data
X.m3b2 <- matrix(NA , nrow = t , ncol = R)
df <- meba.simdata(t + 200)
ll <- seq(from = 0 , by = -1 , length.out = R) # ll as c(0,-1,-2,-3,..)
cf <- rep(1 , R) # Same for all cf as 1

for (m in 1:floor(R * 0.2)){
  X.m3b2[ , m] <- cf[m] * df$bL2f15[(101 + ll[m]):(t + 100 + ll[m])]
}      

for (m in (floor(R * 0.2) + 1):R){
  X.m3b2[ , m] <- cf[m] * df$bS2f35[(101 + ll[m]):(t + 100 + ll[m])]
}

# Plot series 
plot.ts(X.m3b2 , main = "Differing Proportions 3 Bands")

# Compute and plot local periodogram and demeaned local periodogram
N <- 2 * floor(t ^ 0.7) - floor(t ^ 0.7 / 2) * 2 # Neighborhood for local periodogram
freq <- seq(0 , floor(N / 2) , by = 1) / N
pse <- fhat_lp(X.m3b2 , N , stdz = FALSE)
gpse <- ghat(pse)

idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(gpse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Demeaned Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

# Run algorithm and store results
m3b2.out <- msboot(nrep = 1000 , X.m3b2 , Wsel = 3 , stdz = FALSE , ncore = 1)

# Plot output
# Plot of observed test statistics across frequencies (red) and the first 50 bootstrap test statistics (black) for each W
par(mfrow = c(3 , 1))
plot(m3b2.out[[2]][[1]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W1' , ylim = c(0 , 90000))
apply(m3b2.out[[2]][[1]][ , 3:50] , 2 , function(x) lines(cbind(m3b2.out[[2]][[1]][ , 1] , x)))
lines(m3b2.out[[1]][[1]] , col = 'red' , lwd = 2)

plot(m3b2.out[[2]][[2]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W2' , ylim = c(0 , 90000))
apply(m3b2.out[[2]][[2]][ , 3:50] , 2 , function(x) lines(cbind(m3b2.out[[2]][[2]][ , 1] , x)))
lines(m3b2.out[[1]][[2]] , col = 'red' , lwd = 2)

plot(m3b2.out[[2]][[3]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W3' , ylim = c(0 , 90000))
apply(m3b2.out[[2]][[3]][ , 3:50] , 2 , function(x) lines(cbind(m3b2.out[[2]][[3]][ , 1] , x)))
lines(m3b2.out[[1]][[3]] , col = 'red' , lwd = 2)

# Plot of p-values for testing each frequency as a partition point (black) and 0.05 threshold (red) for each W
par(mfrow = c(3 , 1))
plot(m3b2.out[[3]][[1]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))

abline(h = 0.05 , col = 'red')
plot(m3b2.out[[3]][[2]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(m3b2.out[[3]][[3]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

# Table of significant frequency partition points (none in the white noise case)
m3b2.out[[4]][which(m3b2.out[[4]][ , 2] == 1) , 1]


# Local periodogram with estimated cutpoints
idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")
abline(h = m3b2.out[[4]][which(m3b2.out[[4]][ , 2] == 1) , 1] , col = 'green' , lwd = 2)
```

```{r simS3B}
set.seed(489)

t <- 200 #Length of time series
R <- 10 # Number of components

##############################
## Sinusoidal 3 Band (S3B)
##############################
# Simulate data
X.s3b <- matrix(NA , nrow = t , ncol = R)
df <- meba.simdata(t + 200)
ll <- seq(from = 0 , by = -1 , length.out = R) # ll as c(0,-1,-2,-3,..)
cf <- rep(1 , R) # Same for all cf as 1

for (m in 1:R){
  X.s3b[ , m] <- cf[m] * df$bS[(101 + ll[m]):(t + 100 + ll[m])]
}

# Plot series 
plot.ts(X.s3b , main = "Sinusoidal 3 Bands")

# Compute and plot local periodogram and demeaned local periodogram
N <- 2 * floor(t ^ 0.7) - floor(t ^ 0.7 / 2) * 2 # Neighborhood for local periodogram
freq <- seq(0 , floor(N / 2) , by = 1) / N
pse <- fhat_lp(X.s3b , N , stdz = FALSE)
gpse <- ghat(pse)

idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(gpse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Demeaned Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

# Run algorithm and store results
s3b.out <- msboot(nrep = 1000 , X.s3b , Wsel = 3 , stdz = FALSE , ncore = 1)

# Plot output
# Plot of observed test statistics across frequencies (red) and the first 50 bootstrap test statistics (black) for each W
par(mfrow = c(3 , 1))
plot(s3b.out[[2]][[1]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W1' , ylim = c(0 , 200000))
apply(s3b.out[[2]][[1]][ , 3:50] , 2 , function(x) lines(cbind(s3b.out[[2]][[1]][ , 1] , x)))
lines(s3b.out[[1]][[1]] , col = 'red' , lwd = 2)

plot(s3b.out[[2]][[2]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W2' , ylim = c(0 , 200000))
apply(s3b.out[[2]][[2]][ , 3:50] , 2 , function(x) lines(cbind(s3b.out[[2]][[2]][ , 1] , x)))
lines(s3b.out[[1]][[2]] , col = 'red' , lwd = 2)

plot(s3b.out[[2]][[3]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W3' , ylim = c(0 , 200000))
apply(s3b.out[[2]][[3]][ , 3:50] , 2 , function(x) lines(cbind(s3b.out[[2]][[3]][ , 1] , x)))
lines(s3b.out[[1]][[3]] , col = 'red' , lwd = 2)

# Plot of p-values for testing each frequency as a partition point (black) and 0.05 threshold (red) for each W
par(mfrow = c(3 , 1))
plot(s3b.out[[3]][[1]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(s3b.out[[3]][[2]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(s3b.out[[3]][[3]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

# Table of significant frequency partition points (none in the white noise case)
s3b.out[[4]][which(s3b.out[[4]][ , 2] == 1) , 1]


# Local periodogram with estimated cutpoints
idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")
abline(h = s3b.out[[4]][which(s3b.out[[4]][ , 2] == 1) , 1] , col = 'green' , lwd = 2)
```

```{r simWN1B}
set.seed(523)

t <- 200 # Length of time series
R <- 10 # Number of components

########################
## White Noise (WN1B)
########################
# Simulate data
X.wn <- matrix(NA , nrow = t , ncol = R)
for (m in 1:R){
  X.wn[ , m] <- meba.simdata(t)$wn
}

# Plot series 
plot.ts(X.wn , main = "White Noise")

# Compute and plot local periodogram and demeaned local periodogram
N <- 2 * floor(t ^ 0.7) - floor(t ^ 0.7 / 2) * 2 # Neighborhood for local periodogram
freq <- seq(0 , floor(N / 2) , by = 1) / N
pse <- fhat_lp(X.wn , N , stdz = FALSE)
gpse <- ghat(pse)

idx <- 1 # Component for which you want to view local periodogram (can be 1,2,..,R)
par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(pse[-1 , idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

par(mfrow = c(1 , 1))
image.plot(x = (1:t) / (t + 1) , y = freq[-1] , z = t(Re(gpse[-1, idx + (idx - 1) * R , ])) , 
           axes = TRUE , col = inferno(256) , main = 'Demeaned Local Periodogram' , 
           xlab = 'Time' , ylab = 'Frequency' , xaxs = "i")

# Run algorithm and store results
wn1b.out <- msboot(nrep = 1000 , X.wn , Wsel = 3 , stdz = FALSE , ncore = 1)

# Plot output
# Plot of observed test statistics across frequencies (red) and the first 50 bootstrap test statistics (black) for each W
par(mfrow = c(3 , 1))
plot(wn1b.out[[2]][[1]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W1' , ylim = c(0 , 6))
apply(wn1b.out[[2]][[1]][ , 3:50] , 2 , function(x) lines(cbind(wn1b.out[[2]][[1]][ , 1] , x)))
lines(wn1b.out[[1]][[1]] , col = 'red' , lwd = 2)

plot(wn1b.out[[2]][[2]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W2' , ylim = c(0 , 6))
apply(wn1b.out[[2]][[2]][ , 3:50] , 2 , function(x) lines(cbind(wn1b.out[[2]][[2]][ , 1] , x)))
lines(wn1b.out[[1]][[2]] , col = 'red' , lwd = 2)

plot(wn1b.out[[2]][[3]][ , 1:2] , type = 'l' , xlab = 'Frequency' , ylab = 'D(omega)' , 
     main = 'W3' , ylim = c(0 , 6))
apply(wn1b.out[[2]][[3]][ , 3:50] , 2 , function(x) lines(cbind(wn1b.out[[2]][[3]][ , 1] , x)))
lines(wn1b.out[[1]][[3]] , col = 'red' , lwd = 2)

# Plot of p-values for testing each frequency as a partition point (black) and 0.05 threshold (red) for each W
par(mfrow = c(3 , 1))
plot(wn1b.out[[3]][[1]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(wn1b.out[[3]][[2]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

plot(wn1b.out[[3]][[3]] , type = 'l' , xlab = 'Frequency' , ylab = 'p-value' , 
     main = 'W1' , ylim = c(0 , 1))
abline(h = 0.05 , col = 'red')

# Table of significant frequency partition points (none in the white noise case)
wn1b.out[[4]][which(wn1b.out[[4]][ , 2] == 1) , 1]

```
