# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ADD TITLE
#' @description ADD DESCRIPTION
#' @param nrep ADD DESCRIPTION
#' @param x ADD DESCRIPTION
#' @param Wsel ADD DESCRIPTION
#' @param stdz ADD DESCRIPTION
#' @param ncore ADD DESCRIPTION
#' @return ADD DESCRIPTION
#' @examples
#' # ADD EXAMPLE
#' @export
msboot <- function(nrep, x, Wsel, stdz, ncore) {
    .Call(`_EFBA_msboot`, nrep, x, Wsel, stdz, ncore)
}

tsbootH0 <- function(x, rndraws, ncore) {
    .Call(`_EFBA_tsbootH0`, x, rndraws, ncore)
}

#' ADD TITLE
#' @description ADD DESCRIPTION
#' @param X ADD DESCRIPTION
#' @param N ADD DESCRIPTION
#' @param stdz ADD DESCRIPTION
#' @return ADD DESCRIPTION
#' @examples
#' # ADD EXAMPLE
#' @export
fhat_lp <- function(X, N, stdz) {
    .Call(`_EFBA_fhat_lp`, X, N, stdz)
}

#' Generate Multitaper Estimator of Power Spectrum for Functional Data
#' @description
#' This function takes in the aforementioned functional data, as well as a few other parameters, and returns the multitaper
#' estimate of the power spectrum for the data. This works in a piecewise manner, hence why it has the suffix _pmt, for piecewise
#' multitaper
#'
#' @param X A T X R matrix of the functional data, where T is the length of the time series, and R is the number of components.
#' @param K The number of tapers to utilize in estimating the local power spectrum. K must satisfy: 1 <= K < floor(N/4 - 1)
#' @param N The number of observations that will be contained in each roughly stationary block. N must satisfy: 30 <= N <= T
#' @param Rsel The number of points within the functional domain that will be used for computing test statistics. Rsel must satisfy: 1 <= Rsel <= R
#' @param stdz A binary indicator to show whether the variance in each stationary block should be standardized.
#' @return A 3-Dimensional matrix containing the multitaper estimator. Its dimensions are A x B x C, where A = floor(N/2 + 1), B = Rsel^2, and C = floor(T / N)
#' @examples
#' nb=15; #number of basis functions used to generate white noise
#' R=5; #number of points in functional domain
#' Ts=200; #length of time series
#' seed=234; #seed for reproducibility
#' X=fws.sim(nb=nb,gsz=R,Ts=Ts,seed=seed);
#' ##estimate and visualize power spectrum estimates for specific components
#' B=5; #number of time blocks
#' N=Ts/B; #number of observations per time block
#' bw=0.04; #bandwidth for multitaper spectral estimator
#' K=max(1,floor(bw*(N+1)-1)); #number of tapers for multitaper spectral estimator
#' std=FALSE; #standardize variance for points in functional domain (TRUE) or not (FALSE)
#' freq=seq(from=0,by=1/N,length.out=floor(N/2)+1); #Fourier frequencies
#' Rsel=4; #number of points in functional domain used for test statistics
#' pse=fhat_pmt(X,N,K,Rsel,std);
#' @details
#'  Every input must be either a Boolean or Numeric, as mentioned above \cr \cr
#' For more information on how this data is simulated, consult the corresponding paper at https://arxiv.org/abs/2102.01784
#' @export
fhat_pmt <- function(X, N, K, Rsel, stdz) {
    .Call(`_EFBA_fhat_pmt`, X, N, K, Rsel, stdz)
}

#' ADD TITLE
#' @description ADD DESCRIPTION
#' @param fhat_pmt ADD DESCRIPTION
#' @return ADD DESCRIPTION
#' @examples
#' # ADD EXAMPLE
#' @export
ghat <- function(fhat_pmt) {
    .Call(`_EFBA_ghat`, fhat_pmt)
}

Qpval <- function(fhat_pmt, K, ndraw, Qts, Qint, blockdiag) {
    .Call(`_EFBA_Qpval`, fhat_pmt, K, ndraw, Qts, Qint, blockdiag)
}

fEBA <- function(fhat_pmt, ghat, K, ndraw, alpha, blockdiag) {
    .Call(`_EFBA_fEBA`, fhat_pmt, ghat, K, ndraw, alpha, blockdiag)
}

rcpp_hello <- function() {
    .Call(`_EFBA_rcpp_hello`)
}

