# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# R package CI with OpenMP enabled on all OSs (brew + llvm/libomp on macOS)

name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel',   http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install OpenMP toolchain (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew update
          brew install llvm libomp
          LLVM=$(brew --prefix llvm)
          OMP=$(brew --prefix libomp)

          echo "${LLVM}/bin" >> $GITHUB_PATH

          mkdir -p ~/.R
          cat > ~/.R/Makevars <<'EOF'

          CC=$(shell brew --prefix llvm)/bin/clang
          CXX=$(shell brew --prefix llvm)/bin/clang++
          CXX11=$(shell brew --prefix llvm)/bin/clang++
          CXX14=$(shell brew --prefix llvm)/bin/clang++
          CXX17=$(shell brew --prefix llvm)/bin/clang++
          CXX20=$(shell brew --prefix llvm)/bin/clang++

          CPPFLAGS += -I$(shell brew --prefix libomp)/include
          CXXFLAGS += -I$(shell brew --prefix libomp)/include -Xpreprocessor -fopenmp
          LDFLAGS  += -L$(shell brew --prefix libomp)/lib -lomp
          EOF

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools, any::rcpp, any::RcppArmadillo, any::testthat, any::covr, any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
